# -*- mode: python ; coding: utf-8 -*-
# 墨软·工作台 macOS 打包配置（在 Mac 上运行，onedir → .app）
# 构建：pyinstaller workbench_mac.spec --noconfirm --clean
# 产物：dist/ModuWorkbench.app

EXCLUDES = [
    # v1.0.0：前端统一 Qt 单栈，不再打包 QtWebEngine
    "PySide6.QtWebEngineCore",
    "PySide6.QtWebEngineWidgets",
    "PySide6.QtWebEngineQuick",
    "PySide6.Qt3DCore",
    "PySide6.Qt3DRender",
    "PySide6.Qt3DExtras",
    "PySide6.Qt3DInput",
    "PySide6.Qt3DLogic",
    "PySide6.QtQuick",
    "PySide6.QtQuickWidgets",
    "PySide6.QtQml",
    "PySide6.QtCharts",
    "PySide6.QtDataVisualization",
    # QtPdf 要留着：文档板块用它把 PDF 逐页渲染到打印机（打印对话框）
    "PySide6.QtBluetooth",
    "PySide6.QtNfc",
    "PySide6.QtPositioning",
    "PySide6.QtSensors",
    "PySide6.QtSerialPort",
    "PySide6.QtSql",
    "PySide6.QtTest",
    "PySide6.QtDesigner",
    "PySide6.QtHelp",
    "PySide6.QtRemoteObjects",
    "PySide6.QtScxml",
    "PySide6.QtStateMachine",
    "PySide6.QtTextToSpeech",
    "tkinter",
]

a = Analysis(
    ["src/modu_workbench/__main__.py"],
    pathex=["src"],
    binaries=[],
    datas=[
        ("src/modu_workbench/assets", "modu_workbench/assets"),
        # 随包 ffmpeg（macOS 为无扩展名二进制；不存在时该行会在打包时报错，
        # 需先放置 tools/ffmpeg/ffmpeg 与 ffprobe）
        ("tools/ffmpeg/ffmpeg", "tools/ffmpeg"),
        ("tools/ffmpeg/ffprobe", "tools/ffmpeg"),
    ],
    hiddenimports=[
        "modu_workbench.boards.book.online",
        "modu_workbench.boards.book.reader",
        "modu_workbench.boards.book.shelf",
        "modu_workbench.boards.convert.board",
        "modu_workbench.boards.convert.doc_viewer",
        "modu_workbench.core.convert.media_io",
        "modu_workbench.core.convert.pdf_out",
        # 分板块设置页（旧版单体 settings_dialog 已拆分为 ui_kit/settings/ 包）
        "modu_workbench.ui_kit.settings",
        "modu_workbench.ui_kit.settings.base",
        # markdown 扩展按名动态加载
        "markdown.extensions.extra",
        "markdown.extensions.fenced_code",
        "markdown.extensions.sane_lists",
        "markdown.extensions.tables",
        "markdown.extensions.attr_list",
        "markdown.extensions.def_list",
        "markdown.extensions.footnotes",
        "markdown.extensions.md_in_html",
        "markdown.extensions.nl2br",
        "markdown.extensions.toc",
        "markdown.extensions.admonition",
        # Pygments 常用词法器（其余回退纯文本）
        "pygments.lexers.data",
        "pygments.lexers.python",
        "pygments.lexers.javascript",
        "pygments.lexers.html",
        "pygments.lexers.css",
        "pygments.lexers.shell",
        "pygments.lexers.sql",
        "pygments.lexers.text",
        "pygments.lexers.markup",
        "pygments.formatters.html",
        # 墨软乐库：板块页面与核心引擎（含 QtMultimedia 播放与在线音源）
        "modu_workbench.boards.music.board",
        "modu_workbench.boards.music.search",
        "modu_workbench.boards.music.library_page",
        "modu_workbench.boards.music.playlist",
        "modu_workbench.boards.music.history",
        "modu_workbench.boards.music.widgets",
        "modu_workbench.core.music.sources",
        "modu_workbench.core.music.sources.http",
        "modu_workbench.core.music.sources.base",
        "modu_workbench.core.music.sources.matcher",
        "modu_workbench.core.music.sources.quality",
        "modu_workbench.core.music.sources.registry",
        "modu_workbench.core.music.sources.providers",
        "modu_workbench.core.music.sources.providers.netease",
        "modu_workbench.core.music.sources.providers.kuwo",
        "modu_workbench.core.music.sources.providers.itunes",
        "modu_workbench.core.music.sources.providers.audius",
        "modu_workbench.core.music.sources.providers.archive_org",
        "modu_workbench.core.music.sources.providers.ccmixter",
        "modu_workbench.core.music.sources.providers.jamendo",
        "modu_workbench.core.music.sources.providers.direct",
        "modu_workbench.core.music.storage",
        "modu_workbench.core.music.downloader",
        "modu_workbench.core.music.library",
        "modu_workbench.core.music.player",
        # 墨软影视：板块页面与核心引擎
        "modu_workbench.boards.video.board",
        "modu_workbench.boards.video.search",
        "modu_workbench.boards.video.library_page",
        "modu_workbench.boards.video.history",
        "modu_workbench.boards.video.detail",
        "modu_workbench.boards.video.sources",
        "modu_workbench.boards.video.player",
        "modu_workbench.boards.video.widgets",
        "modu_workbench.core.video.models",
        "modu_workbench.core.video.storage",
        "modu_workbench.core.video.library",
        "modu_workbench.core.video.hls",
        "modu_workbench.core.video.downloader",
        "modu_workbench.core.video.sources",
        "modu_workbench.core.video.sources.http",
        "modu_workbench.core.video.sources.base",
        "modu_workbench.core.video.sources.matcher",
        "modu_workbench.core.video.sources.registry",
        "modu_workbench.core.video.sources.providers",
        "modu_workbench.core.video.sources.providers.cms_vod",
        "modu_workbench.core.video.sources.providers.public",
        # 墨软图库
        "modu_workbench.boards.gallery.board",
        "modu_workbench.boards.gallery.widgets",
        "modu_workbench.boards.gallery.editor",
        "modu_workbench.boards.gallery.enhance",
        "modu_workbench.core.gallery.models",
        "modu_workbench.core.gallery.storage",
        "modu_workbench.core.gallery.library",
        "modu_workbench.core.gallery.hashing",
        "modu_workbench.core.gallery.exif",
        "modu_workbench.core.gallery.thumbs",
        "modu_workbench.core.gallery.edits",
        "modu_workbench.core.gallery.enhance",
        "modu_workbench.core.gallery.ai",
        # 墨软文档：板块页面与核心引擎（解析/美化/计算/合并/AI 工具与循环）＋设置页
        "modu_workbench.boards.document.board",
        "modu_workbench.boards.document.context",
        "modu_workbench.boards.document.viewer",
        "modu_workbench.boards.document.beautify_page",
        "modu_workbench.boards.document.sheet_page",
        "modu_workbench.boards.document.merge_page",
        "modu_workbench.boards.document.loop_page",
        "modu_workbench.boards.document.security_page",
        "modu_workbench.boards.document.pdf_dialog",
        "modu_workbench.boards.document.widgets",
        "modu_workbench.core.document.models",
        "modu_workbench.core.document.formats",
        "modu_workbench.core.document.parser",
        "modu_workbench.core.document.writer",
        "modu_workbench.core.document.beautify",
        "modu_workbench.core.document.sheet",
        "modu_workbench.core.document.merge",
        "modu_workbench.core.document.quality",
        "modu_workbench.core.document.security",
        "modu_workbench.core.document.tools",
        "modu_workbench.core.document.ai",
        "modu_workbench.core.document.loop",
        "modu_workbench.core.document.library",
        "modu_workbench.core.document.storage",
        "modu_workbench.core.document.pdf_tools",
        "modu_workbench.core.document.templates",
        "modu_workbench.core.document.plugins",
        "modu_workbench.core.document.ocr",
        # 大模型能力中心：多类型/多配置/优先级降级
        "modu_workbench.core.llm.models",
        "modu_workbench.core.llm.router",
        "modu_workbench.ui_kit.settings.general",
        "modu_workbench.ui_kit.settings.book",
        "modu_workbench.ui_kit.settings.convert",
        "modu_workbench.ui_kit.settings.document",
        "modu_workbench.ui_kit.settings.music",
        "modu_workbench.ui_kit.settings.video",
        "modu_workbench.ui_kit.settings.gallery",
        "modu_workbench.ui_kit.settings.llm",
        "numpy",
        "pypdf",
        "PIL.Image",
        "PIL.ImageOps",
        "PIL.ImageFilter",
        "PIL.ImageEnhance",
        "PIL.ExifTags",
        "PySide6.QtMultimedia",
        "PySide6.QtMultimediaWidgets",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=EXCLUDES,
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="ModuWorkbench",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    argv_emulation=True,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    name="ModuWorkbench",
)
app = BUNDLE(
    coll,
    name="ModuWorkbench.app",
    # macOS 使用 .icns；PyInstaller 可借 Pillow 由 .ico 转换（若失败可先转成 app.icns）
    icon="src/modu_workbench/assets/app.ico",
    bundle_identifier="com.internal.moduworkbench",
    info_plist={
        "NSHighResolutionCapable": True,
        "LSMinimumSystemVersion": "11.0",
        "CFBundleDisplayName": "墨软·工作台",
        "CFBundleShortVersionString": "1.0.5",
    },
)
