# -*- mode: python ; coding: utf-8 -*-
# 墨软·工作台 macOS 打包配置（在 Mac 上运行，onedir → .app）
# 构建：pyinstaller workbench_mac.spec --noconfirm --clean
# 产物：dist/ModuWorkbench.app

EXCLUDES = [
    "PySide6.Qt3DCore",
    "PySide6.Qt3DRender",
    "PySide6.Qt3DExtras",
    "PySide6.QtQuick",
    "PySide6.QtQuickWidgets",
    "PySide6.QtQml",
    "PySide6.QtCharts",
    "PySide6.QtDataVisualization",
    "PySide6.QtBluetooth",
    "PySide6.QtNfc",
    "PySide6.QtPositioning",
    "PySide6.QtSensors",
    "PySide6.QtSerialPort",
    "PySide6.QtSql",
    "PySide6.QtTest",
    "PySide6.QtDesigner",
    "PySide6.QtHelp",
    "tkinter",
]

a = Analysis(
    ["src/modu_workbench/__main__.py"],
    pathex=["src"],
    binaries=[],
    datas=[
        ("src/modu_workbench/webfront", "modu_workbench/webfront"),
        ("src/modu_workbench/assets", "modu_workbench/assets"),
        # 随包 ffmpeg（macOS 为无扩展名二进制；不存在时该行会在打包时报错，
        # 需先放置 tools/ffmpeg/ffmpeg 与 ffprobe）
        ("tools/ffmpeg/ffmpeg", "tools/ffmpeg"),
        ("tools/ffmpeg/ffprobe", "tools/ffmpeg"),
    ],
    hiddenimports=[
        "modu_workbench.boards.book_online",
        "modu_workbench.boards.book_reader",
        "modu_workbench.boards.book_shelf",
        "modu_workbench.boards.convert_board",
        "modu_workbench.boards.convert_web",
        "modu_workbench.boards.doc_viewer",
        "modu_workbench.core.convert.media_io",
        "modu_workbench.core.convert.pdf_out",
        "modu_workbench.services.web_bridge",
        # 分板块设置页（旧版单体 settings_dialog 已拆分为 ui_kit/settings/ 包）
        "modu_workbench.ui_kit.settings",
        "modu_workbench.ui_kit.settings.base",
        "PySide6.QtWebEngineWidgets",
        "PySide6.QtWebEngineCore",
        "PySide6.QtWebChannel",
        "markdown.extensions.extra",
        "markdown.extensions.fenced_code",
        "markdown.extensions.sane_lists",
        "markdown.extensions.tables",
        "pygments.lexers.data",
        "pygments.lexers.python",
        "pygments.lexers.javascript",
        "pygments.lexers.html",
        "pygments.lexers.css",
        "pygments.lexers.shell",
        "pygments.lexers.sql",
        "pygments.lexers.text",
        "pygments.formatters.html",
        # 墨软影视：板块页面与核心引擎
        "modu_workbench.boards.video_board",
        "modu_workbench.boards.video_search",
        "modu_workbench.boards.video_library_page",
        "modu_workbench.boards.video_history",
        "modu_workbench.boards.video_detail",
        "modu_workbench.boards.video_sources",
        "modu_workbench.boards.video_player",
        "modu_workbench.boards.video_widgets",
        "modu_workbench.core.video.models",
        "modu_workbench.core.video.storage",
        "modu_workbench.core.video.library",
        "modu_workbench.core.video.hls",
        "modu_workbench.core.video.downloader",
        "modu_workbench.core.video.sources",
        "modu_workbench.core.video.sources.providers.cms_vod",
        "modu_workbench.core.video.sources.providers.public",
        # 墨软图库
        "modu_workbench.boards.gallery_board",
        "modu_workbench.boards.gallery_widgets",
        "modu_workbench.boards.gallery_editor",
        "modu_workbench.boards.gallery_enhance",
        "modu_workbench.core.image.models",
        "modu_workbench.core.image.storage",
        "modu_workbench.core.image.library",
        "modu_workbench.core.image.hashing",
        "modu_workbench.core.image.exif",
        "modu_workbench.core.image.thumbs",
        "modu_workbench.core.image.edits",
        "modu_workbench.core.image.enhance",
        "modu_workbench.core.image.ai",
        "modu_workbench.ui_kit.settings.gallery",
        "numpy",
        "PIL.Image",
        "PIL.ImageOps",
        "PIL.ImageFilter",
        "PIL.ImageEnhance",
        "PIL.ExifTags",
        "PySide6.QtMultimedia",
        "PySide6.QtMultimediaWidgets",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=EXCLUDES,
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="ModuWorkbench",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    argv_emulation=True,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    name="ModuWorkbench",
)
app = BUNDLE(
    coll,
    name="ModuWorkbench.app",
    # macOS 使用 .icns；PyInstaller 可借 Pillow 由 .ico 转换（若失败可先转成 app.icns）
    icon="src/modu_workbench/assets/app.ico",
    bundle_identifier="com.internal.moduworkbench",
    info_plist={
        "NSHighResolutionCapable": True,
        "LSMinimumSystemVersion": "11.0",
        "CFBundleDisplayName": "墨软·工作台",
        "CFBundleShortVersionString": "0.3.0",
    },
)
