"""墨软文档板块引擎（第六大板块）。

对外入口（界面层只依赖这里）：

    from modu_workbench.core.document import (
        DocumentLibrary, DocumentStorage, DocumentAi,
        BeautifyOptions, LoopOptions, MergeOptions,
        parse_document, write_document,
    )

模块划分（对应 PRD 的三层 + 能力块）：

| 模块 | 职责 | 对应需求 |
|---|---|---|
| `formats.py` | 格式能力矩阵（查看/编辑/转换/批注/OCR） | 6.2 |
| `parser.py` | 各格式 → 统一中间结构 `DocumentIR` | 6.2 / 6.6 解析层 |
| `writer.py` | `DocumentIR` → txt/md/html/docx/xlsx/csv/tsv/json/pdf | 6.2 / 6.3 导出 |
| `beautify.py` | 一键美化、模板、样式统一、表格、编号、目录、品牌 | 6.3 |
| `sheet.py` | 自动填充、智能填充、公式计算、统计、检查、AI 公式 | 6.4 |
| `ai.py` | 场景（角色）、工具调用循环、质量评估、权限与日志 | 6.5 |
| `tools.py` | 工具注册表（AI 与界面共用同一套工具） | 6.5 |
| `merge.py` | 两个文档合并（七种模式）+ 差异报告 + 摘要 | 6.6 |
| `loop.py` | AI 循环美化引擎（分析→计划→工具→评分→停止） | 6.7 |
| `quality.py` | 文档体检、五维质量评分、结构化 diff | 6.7 |
| `security.py` | 脱敏、权限、水印与追踪、审计字典 | 6.8 |
| `storage.py` | `doc_*` 表：文档库/版本快照/合并报告/AI 与审计日志 | 6.8 |
| `library.py` | 业务编排（界面唯一入口） | 全部 |
| `ocr.py` | 可选 OCR（tesseract / PyMuPDF） | 6.2 图片与扫描 |
"""
from __future__ import annotations

from .ai import (
    SCENES,
    SCENE_KEYS,
    SCENE_LABELS,
    AgentResult,
    AiUnavailable,
    DocumentAi,
    SceneSpec,
    capability_text as ai_capability_text,
    heuristic_plan,
    local_polish,
    local_transform,
    parse_agent_reply,
    parse_plan_reply,
    parse_score_reply,
    scene_choices,
    scene_matrix,
)
from .beautify import (
    TEMPLATES,
    TemplateSpec,
    beautify as beautify_document,      # 刻意改名：避免遮蔽同名的 beautify 子模块
    template_choices,
    template_label,
    template_matrix,
    template_options,
)
from .formats import (
    CATEGORY_LABELS,
    CATEGORY_ORDER,
    EXPORT_EXTENSIONS,
    EXPORT_TARGETS,
    FORMAT_BY_KEY,
    FORMAT_SPECS,
    DocFormatSpec,
    category_label,
    describe_matrix,
    export_label,
    extensions_for_dialog,
    format_key_for_path,
    format_label,
    get_spec,
    is_supported,
    spec_for_path,
    summary_text,
)
from .library import DocumentLibrary
from .loop import BeautifyLoop, LoopEvent, run_loop
from .merge import (
    build_summary,
    capability_text as merge_capability_text,
    conflict_scan,
    dedupe_blocks,
    diff_documents,
    extractive_summary,
    merge_documents,
    merge_preview_lines,
    merge_table_columns,
    merge_table_key,
    merge_table_rows,
    unify_terms,
)
from .models import (
    BLOCK_CODE,
    BLOCK_HEADING,
    BLOCK_IMAGE,
    BLOCK_PARAGRAPH,
    BLOCK_TABLE,
    BLOCK_TOC,
    BeautifyOptions,
    BeautifyResult,
    Block,
    Change,
    DiffLine,
    DocumentIR,
    LoopOptions,
    LoopResult,
    MERGE_MODES,
    MERGE_MODE_LABELS,
    MergeOptions,
    MergeReport,
    MergeResult,
    QualityScore,
    RoundReport,
    STOP_LABELS,
    TableData,
    ToolCallRecord,
)
from .parser import (
    MAX_TABLE_ROWS,
    ParseError,
    format_structured,
    guess_heading_level,
    parse_document,
    parse_html,
    parse_markdown,
    parse_plain_text,
    read_document_text,
    sniff_ooxml,
)
from .pdf_tools import (
    PdfError,
    PdfInfo,
    annotate_pdf,
    compress_pdf,
    decrypt_pdf,
    encrypt_pdf,
    extract_pages,
    fill_form,
    list_annotations,
    list_form_fields,
    merge_pdfs,
    parse_pages,
    pdf_info,
    rotate_pdf,
    split_pdf,
    watermark_pdf,
)
from .quality import analyze_document, diff_irs, heuristic_score
from .security import (
    AUDIT_ACTIONS,
    DEFAULT_MASK_RULES,
    MASK_RULES,
    MaskReport,
    MaskRule,
    Permissions,
    audit_label,
    audit_line,
    build_watermark,
    describe_watermark,
    is_local_profile,
    mask_document,
    mask_label,
    mask_rule_choices,
    mask_text,
    new_tracking_id,
    permissions_from_settings,
    scan_sensitive,
)
from .sheet import (
    CUSTOM_LISTS,
    FILTER_MODES,
    FUNCTIONS,
    FUNCTION_NAMES,
    Array,
    CellRef,
    FormulaEngine,
    FormulaError,
    PatternSpec,
    SeriesSpec,
    apply_pattern,
    autofill,
    cell_value,
    chart_series,
    check_formulas,
    column_index,
    column_letters,
    convert_units,
    detect_series,
    distinct_values,
    evaluate_formula,
    explain_formula,
    fill_series,
    filter_table,
    formula_prompt,
    group_by,
    infer_pattern,
    infer_patterns,
    parse_cell_ref,
    parse_date,
    pivot,
    repair_formula,
    resolved_matrix,
    sheet_name_of,
    smart_fill,
    sort_table,
    suggest_formula,
    summarize_column,
    summarize_table,
    to_number,
    to_text,
    translate_formula,
    unit_categories,
    units_of,
)
from .storage import DocumentRecord, DocumentStorage
from .templates import (
    TemplateError,
    UserTemplate,
    delete_template,
    export_template,
    import_template,
    list_user_templates,
    load_template,
    save_template,
    template_dir,
)
from .tools import (
    TOOL_CATEGORIES,
    TOOL_REGISTRY,
    ToolContext,
    ToolResult,
    ToolSpec,
    call_tool,
    catalog_lines,
    register_tool,
    tool,
    tool_names,
    tools_in_category,
)
from .writer import (
    WatermarkOptions,
    WriteError,
    WriteResult,
    render_html,
    render_markdown,
    render_text,
    unique_output_path,
    write_document,
)

__all__ = [
    "AUDIT_ACTIONS",
    "AgentResult",
    "AiUnavailable",
    "Array",
    "BLOCK_CODE",
    "BLOCK_HEADING",
    "BLOCK_IMAGE",
    "BLOCK_PARAGRAPH",
    "BLOCK_TABLE",
    "BLOCK_TOC",
    "BeautifyLoop",
    "BeautifyOptions",
    "BeautifyResult",
    "Block",
    "CATEGORY_LABELS",
    "CATEGORY_ORDER",
    "CUSTOM_LISTS",
    "CellRef",
    "Change",
    "DEFAULT_MASK_RULES",
    "DiffLine",
    "DocFormatSpec",
    "DocumentAi",
    "DocumentIR",
    "DocumentLibrary",
    "DocumentRecord",
    "DocumentStorage",
    "EXPORT_EXTENSIONS",
    "EXPORT_TARGETS",
    "FILTER_MODES",
    "FORMAT_BY_KEY",
    "FORMAT_SPECS",
    "FUNCTIONS",
    "FUNCTION_NAMES",
    "FormulaEngine",
    "FormulaError",
    "LoopEvent",
    "LoopOptions",
    "LoopResult",
    "MASK_RULES",
    "MAX_TABLE_ROWS",
    "MERGE_MODES",
    "MERGE_MODE_LABELS",
    "MaskReport",
    "MaskRule",
    "MergeOptions",
    "MergeReport",
    "MergeResult",
    "ParseError",
    "PatternSpec",
    "Permissions",
    "PdfError",
    "PdfInfo",
    "QualityScore",
    "RoundReport",
    "SCENES",
    "SCENE_KEYS",
    "SCENE_LABELS",
    "STOP_LABELS",
    "SceneSpec",
    "SeriesSpec",
    "TEMPLATES",
    "TOOL_CATEGORIES",
    "TOOL_REGISTRY",
    "TableData",
    "TemplateError",
    "TemplateSpec",
    "ToolCallRecord",
    "ToolContext",
    "ToolResult",
    "ToolSpec",
    "UserTemplate",
    "WatermarkOptions",
    "WriteError",
    "WriteResult",
    "ai_capability_text",
    "analyze_document",
    "annotate_pdf",
    "apply_pattern",
    "audit_label",
    "audit_line",
    "autofill",
    "beautify_document",
    "build_summary",
    "build_watermark",
    "call_tool",
    "category_label",
    "cell_value",
    "chart_series",
    "catalog_lines",
    "check_formulas",
    "column_index",
    "column_letters",
    "compress_pdf",
    "conflict_scan",
    "convert_units",
    "decrypt_pdf",
    "dedupe_blocks",
    "describe_matrix",
    "describe_watermark",
    "detect_series",
    "diff_documents",
    "diff_irs",
    "distinct_values",
    "encrypt_pdf",
    "evaluate_formula",
    "explain_formula",
    "export_label",
    "export_template",
    "extensions_for_dialog",
    "extract_pages",
    "extractive_summary",
    "fill_form",
    "fill_series",
    "filter_table",
    "format_key_for_path",
    "format_label",
    "format_structured",
    "formula_prompt",
    "get_spec",
    "group_by",
    "guess_heading_level",
    "heuristic_plan",
    "heuristic_score",
    "infer_pattern",
    "infer_patterns",
    "import_template",
    "is_local_profile",
    "is_supported",
    "list_annotations",
    "list_form_fields",
    "list_user_templates",
    "load_template",
    "local_polish",
    "local_transform",
    "mask_document",
    "mask_label",
    "mask_rule_choices",
    "mask_text",
    "merge_documents",
    "merge_capability_text",
    "merge_pdfs",
    "merge_preview_lines",
    "merge_table_columns",
    "merge_table_key",
    "merge_table_rows",
    "new_tracking_id",
    "parse_cell_ref",
    "parse_date",
    "parse_agent_reply",
    "parse_document",
    "parse_html",
    "parse_markdown",
    "parse_pages",
    "parse_plain_text",
    "parse_plan_reply",
    "parse_score_reply",
    "pdf_info",
    "permissions_from_settings",
    "pivot",
    "read_document_text",
    "register_tool",
    "render_html",
    "render_markdown",
    "render_text",
    "repair_formula",
    "resolved_matrix",
    "rotate_pdf",
    "run_loop",
    "save_template",
    "scan_sensitive",
    "scene_choices",
    "scene_matrix",
    "sheet_name_of",
    "smart_fill",
    "sniff_ooxml",
    "sort_table",
    "spec_for_path",
    "split_pdf",
    "suggest_formula",
    "summarize_column",
    "summarize_table",
    "summary_text",
    "template_choices",
    "template_dir",
    "template_label",
    "template_matrix",
    "template_options",
    "to_number",
    "to_text",
    "tool",
    "tool_names",
    "tools_in_category",
    "translate_formula",
    "unit_categories",
    "units_of",
    "unify_terms",
    "unique_output_path",
    "watermark_pdf",
    "write_document",
]
